name: Daniel Birdsall
favicon: null
layout_spectrum: 0.96741
typography_spectrum: 0.58272
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d1b085'
    - '#040000'
    - '#ec750d'
    - '#987751'
    - '#63431d'
  brandStrength: 0.1875
  lightness: 0.5625
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
