name: Daniel Birdsall
favicon: null
layout_spectrum: 0.11438861396163702
typography_spectrum: 0.3340773575473577
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6013255955185741
  lightness: 0.9835324750747532
  saturation: 0.03789604315534234
  rhythmicContrast: 0.5938621712848544
purpose: []
