name: Universal Decay and Conscious Action
favicon: null
layout_spectrum: 0.67652
typography_spectrum: 0.58272
title: 'Universal Decay and Conscious Action '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d1b085'
    - '#040000'
    - '#ec750d'
    - '#987751'
    - '#63431d'
  brandStrength: 0.875
  lightness: 0.1875
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
