name: Universal Decay and Conscious Action
favicon: null
layout_spectrum: 0.67652
typography_spectrum: 0.58272
title: Conscious Actions of Universal Entropy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ebeae6'
    - '#534b5a'
    - '#a4765c'
    - '#429686'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
